name: Upbit Recommender Schedule

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  recommend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install python-dotenv requests pyupbit websocket-client pandas numpy pytz

      - name: Copy secrets to .env
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env

      - name: Run one-shot recommender
        run: python run_once.py
